# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc-api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from google.protobuf.empty_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpc-api.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x0cStatusOutput\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x11\n\x0fGreetingV1Input\"#\n\x10GreetingV1Output\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0fGreetingV2Input\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10GreetingV2Output\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0e\n\x0cHealthzInput\"\x1f\n\x11ResourceV1IdInput\x12\n\n\x02id\x18\x01 \x01(\x04\"P\n\x10ResourceV1Output\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.StatusOutput\x12\x1d\n\x08resource\x18\x02 \x01(\x0b\x32\x0b.ResourceV1\"8\n\nResourceV1\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08owner_id\x18\x02 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\"6\n\x07OwnerV1\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"L\n\x0bResourcesV1\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.StatusOutput\x12\x1e\n\tresources\x18\x02 \x03(\x0b\x32\x0b.ResourceV12G\n\x0fGreetingV1Proto\x12\x34\n\x0bGetGreeting\x12\x10.GreetingV1Input\x1a\x11.GreetingV1Output\"\x00\x32G\n\x0fGreetingV2Proto\x12\x34\n\x0bGetGreeting\x12\x10.GreetingV2Input\x1a\x11.GreetingV2Output\"\x00\x32;\n\x0cHealthzProto\x12+\n\tGetHealth\x12\r.HealthzInput\x1a\r.StatusOutput\"\x00\x32\xf8\x01\n\x0fResourceV1Proto\x12.\n\x04List\x12\x16.google.protobuf.Empty\x1a\x0c.ResourcesV1\"\x00\x12.\n\x03Get\x12\x12.ResourceV1IdInput\x1a\x11.ResourceV1Output\"\x00\x12*\n\x06\x43reate\x12\x0b.ResourceV1\x1a\x11.ResourceV1Output\"\x00\x12*\n\x06Modify\x12\x0b.ResourceV1\x1a\x11.ResourceV1Output\"\x00\x12-\n\x06Remove\x12\x12.ResourceV1IdInput\x1a\r.StatusOutput\"\x00P\x00\x62\x06proto3')



_STATUSOUTPUT = DESCRIPTOR.message_types_by_name['StatusOutput']
_GREETINGV1INPUT = DESCRIPTOR.message_types_by_name['GreetingV1Input']
_GREETINGV1OUTPUT = DESCRIPTOR.message_types_by_name['GreetingV1Output']
_GREETINGV2INPUT = DESCRIPTOR.message_types_by_name['GreetingV2Input']
_GREETINGV2OUTPUT = DESCRIPTOR.message_types_by_name['GreetingV2Output']
_HEALTHZINPUT = DESCRIPTOR.message_types_by_name['HealthzInput']
_RESOURCEV1IDINPUT = DESCRIPTOR.message_types_by_name['ResourceV1IdInput']
_RESOURCEV1OUTPUT = DESCRIPTOR.message_types_by_name['ResourceV1Output']
_RESOURCEV1 = DESCRIPTOR.message_types_by_name['ResourceV1']
_OWNERV1 = DESCRIPTOR.message_types_by_name['OwnerV1']
_RESOURCESV1 = DESCRIPTOR.message_types_by_name['ResourcesV1']
StatusOutput = _reflection.GeneratedProtocolMessageType('StatusOutput', (_message.Message,), {
  'DESCRIPTOR' : _STATUSOUTPUT,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:StatusOutput)
  })
_sym_db.RegisterMessage(StatusOutput)

GreetingV1Input = _reflection.GeneratedProtocolMessageType('GreetingV1Input', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGV1INPUT,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:GreetingV1Input)
  })
_sym_db.RegisterMessage(GreetingV1Input)

GreetingV1Output = _reflection.GeneratedProtocolMessageType('GreetingV1Output', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGV1OUTPUT,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:GreetingV1Output)
  })
_sym_db.RegisterMessage(GreetingV1Output)

GreetingV2Input = _reflection.GeneratedProtocolMessageType('GreetingV2Input', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGV2INPUT,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:GreetingV2Input)
  })
_sym_db.RegisterMessage(GreetingV2Input)

GreetingV2Output = _reflection.GeneratedProtocolMessageType('GreetingV2Output', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGV2OUTPUT,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:GreetingV2Output)
  })
_sym_db.RegisterMessage(GreetingV2Output)

HealthzInput = _reflection.GeneratedProtocolMessageType('HealthzInput', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHZINPUT,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:HealthzInput)
  })
_sym_db.RegisterMessage(HealthzInput)

ResourceV1IdInput = _reflection.GeneratedProtocolMessageType('ResourceV1IdInput', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEV1IDINPUT,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:ResourceV1IdInput)
  })
_sym_db.RegisterMessage(ResourceV1IdInput)

ResourceV1Output = _reflection.GeneratedProtocolMessageType('ResourceV1Output', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEV1OUTPUT,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:ResourceV1Output)
  })
_sym_db.RegisterMessage(ResourceV1Output)

ResourceV1 = _reflection.GeneratedProtocolMessageType('ResourceV1', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEV1,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:ResourceV1)
  })
_sym_db.RegisterMessage(ResourceV1)

OwnerV1 = _reflection.GeneratedProtocolMessageType('OwnerV1', (_message.Message,), {
  'DESCRIPTOR' : _OWNERV1,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:OwnerV1)
  })
_sym_db.RegisterMessage(OwnerV1)

ResourcesV1 = _reflection.GeneratedProtocolMessageType('ResourcesV1', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCESV1,
  '__module__' : 'grpc_api_pb2'
  # @@protoc_insertion_point(class_scope:ResourcesV1)
  })
_sym_db.RegisterMessage(ResourcesV1)

_GREETINGV1PROTO = DESCRIPTOR.services_by_name['GreetingV1Proto']
_GREETINGV2PROTO = DESCRIPTOR.services_by_name['GreetingV2Proto']
_HEALTHZPROTO = DESCRIPTOR.services_by_name['HealthzProto']
_RESOURCEV1PROTO = DESCRIPTOR.services_by_name['ResourceV1Proto']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSOUTPUT._serialized_start=47
  _STATUSOUTPUT._serialized_end=92
  _GREETINGV1INPUT._serialized_start=94
  _GREETINGV1INPUT._serialized_end=111
  _GREETINGV1OUTPUT._serialized_start=113
  _GREETINGV1OUTPUT._serialized_end=148
  _GREETINGV2INPUT._serialized_start=150
  _GREETINGV2INPUT._serialized_end=181
  _GREETINGV2OUTPUT._serialized_start=183
  _GREETINGV2OUTPUT._serialized_end=218
  _HEALTHZINPUT._serialized_start=220
  _HEALTHZINPUT._serialized_end=234
  _RESOURCEV1IDINPUT._serialized_start=236
  _RESOURCEV1IDINPUT._serialized_end=267
  _RESOURCEV1OUTPUT._serialized_start=269
  _RESOURCEV1OUTPUT._serialized_end=349
  _RESOURCEV1._serialized_start=351
  _RESOURCEV1._serialized_end=407
  _OWNERV1._serialized_start=409
  _OWNERV1._serialized_end=463
  _RESOURCESV1._serialized_start=465
  _RESOURCESV1._serialized_end=541
  _GREETINGV1PROTO._serialized_start=543
  _GREETINGV1PROTO._serialized_end=614
  _GREETINGV2PROTO._serialized_start=616
  _GREETINGV2PROTO._serialized_end=687
  _HEALTHZPROTO._serialized_start=689
  _HEALTHZPROTO._serialized_end=748
  _RESOURCEV1PROTO._serialized_start=751
  _RESOURCEV1PROTO._serialized_end=999
# @@protoc_insertion_point(module_scope)
